export default {
	ADD_NAME: 'ADD_NAME',
	ADD_MAIL: 'ADD_MAIL',
	ADD_PHONE: 'ADD_PHONE',
	ADD_MODEL: 'ADD_MODEL',
	ADD_BRAND: 'ADD_BRAND',
	ADD_TYPE: 'ADD_TYPE',
	ADD_WHERE_TO_FIX: 'ADD_WHERE_TO_FIX',
	ADD_DESCRIPTION: 'ADD_DESCRIPTION'
}
